Parameters:
  RepositoryName:
    Type: String
    Description: The name of the ECR repository to store images

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowLambdaToGetAuthorizationToken
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: ecr:GetAuthorizationToken
          - Sid: AllowLambdaToPullImages
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
